### ISSUE TITLE
Misses Flag england rounded

### ISSUE THREAD

**Issue by filpunisher** [iconify/collections-json#10]
the round flag of england is missing

**Comment by cyberalien** [comment]
In which icon set?

**Comment by filpunisher** [comment]
Hi cyberalien, in https://iconify.design/icon-sets/emojione/ are missing in the version coloured and uncoloured

**Comment by cyberalien** [comment]
That icon set supports only old set of emojis, when flag of England emoji didn't exist yet.

Unfortunately creators of that icon set decided to go commercial, so newer version, which probably includes flag of England, cannot be used in open source projects.

**Comment by filpunisher** [comment]
hi,
 i created this, you think you can implement it


[england-flag-rounded.svg.zip](https://github.com/iconify/collections-json/files/5311464/england-flag-rounded.svg.zip)

**Comment by cyberalien** [comment]
Usually such icons should be added by icon set authors, but since it is no longer updated, I think exception can be made.

Added icon to EmojiOne set. Also added matching icon for Scotland because... why not. 😀

However I've slightly modified it. Your icon had an empty background, which I guess was an export error of software you have used. In future you can try Figma for customising icons, it is really good. Figma has very powerful vector tools that are pixel perfect and Figma is free.

**Comment by filpunisher** [comment]
Perfect thanks :)
