### ISSUE TITLE
Gala icons

### ISSUE THREAD

**Issue by sisyphusion** [iconify/collections-json#14]
Hello, I am interested in having my icon set published on Iconify.

https://github.com/sisyphusion/gala-icons

Thank you!

**Comment by cyberalien** [comment]
Sure. I see you have 2 icon variations: regular and thin. How would you prefer to handle variations? Icons will need to have either prefix or suffix added. For example, for `add` icon it can be `gala:add` for regular icon and `gala:add-thin` for thin icon.

**Comment by sisyphusion** [comment]
Apologies for taking so long to get back to you, I haven't had the opportunity to work on this in a while. I've since made some improvements to the regular icons and renamed them using the gala:icon format you've sugguested. The thin variants (gala:icon-thin) will be re-added shortly.

**Comment by cyberalien** [comment]
Thanks. 

I think you misunderstood naming. No need to add `gala:` to icon names, I was asking about suffix or prefix for icons because icons in both directories had the same names. But no worries, import script can handle anything :) 

I'm confused by viewBox. Icons use viewBox="0 0 67.733332 67.733333" and all shapes use floating point coordinates too. Yet width and height are set to 256. So if icon is scaled to 256x256, shapes do end up on nice grid, but scaling is never perfect so there could be rounded numbers. Icon code exported by Inkscape is terrible. Can you export icons with proper viewBox so there wouldn't be any rounding errors?

**Comment by cyberalien** [comment]
Tried scaling them in import to 256x256, icons end up with stroke-width="15.999" and similar incorrect numbers in all attributes. So icons need to be re-exported with correct grid.

**Comment by sisyphusion** [comment]
Figured out what caused the viewbox weirdness and have begun re-adding them. Viewbox is now 0 0 256 256.

**Comment by cyberalien** [comment]
Ran script to check icons, looks like Inkscape just scaled icons up during export process. It didn't actually place them on proper grid. Most icons have things like r="32.004" and paths like d="M16.057 ...", few icons contain transformation matrix.

Icons are usable and those minor things won't be noticed, so icon set does look good.

**Comment by sisyphusion** [comment]
Okay, that's fine for now if you're good with it. I'll continue working with them to see if I can clean up some of that.

**Comment by cyberalien** [comment]
Added.

It might take a while to appear because of cache.
