### ISSUE TITLE
add Nova icons

### ISSUE THREAD

**Issue by hanakin** [iconify/collections-json#2]
suggest adding Nova free icons and free emojis

https://www.webalys.com/nova/free-icons.html (https://creativecommons.org/publicdomain/zero/1.0/)
http://emoji.streamlineicons.com/ (https://creativecommons.org/licenses/by/4.0/)

**Comment by cyberalien** [comment]
Those are excellent icon sets, but looks like they are impossible to maintain. This repository is updated automatically few times a day from public sources where icon sets are maintained: GitHub repositories, NPM packages. Whole process is automated and does not require any input.

Those icon sets are on websites with download links that require subscriptions, I don't see any public repositories for them. Its not something that can be automated.

But I'll see what can be done.

**Comment by cyberalien** [comment]
I'll close this for now.

Its in my todo list to make it possible for users to publish and maintain their own icon sets, both private and public. So it will be implemented, anyone would be able to upload and maintain those icon sets for their own use or for use with their software.

It will take a while to implement though because my todo list is massive. Currently I'm working on icon finder component, which is a simple customisable script that searches icons, so it can be integrated into any software to allow users to find icons directly from that software (should be ready this month). Then I plan to make Vue and Angular components similar to React component. Then updating Sketch and Figma plugins, writing Adobe XD plugin (based on that icon finder component). Then rewrite whole documentation and few other parts of website. Only then I can start thinking about adding ability to publish public and private icon sets, which will also require rewriting API scripts to support many repositories and some kind of authentication. Its a huge project with massive todo list.
