### ISSUE TITLE
Icon Sets

### ISSUE THREAD

**Issue by swapnilsarwe** [iconify/collections-json#20]
Came across couple of icon sets:
- https://github.com/primefaces/primeicons
- https://github.com/emblemicons/emblemicons.github.io

**Comment by cyberalien** [comment]
Added PrimeIcons.

Didn't add Emblemicons because they are rather bad. Many icons, for example, "delete-fill" use white fill instead of masks in areas that are supposed to be transparent. That means icons can be used only with white background and color should not be changed, which is really bad assumption.
