### ISSUE TITLE
Mono Icons twice

### ISSUE THREAD

**Issue by bennetfabian** [iconify/collections-json#21]
Why are Mono Icons available under two different names?
mi.json as well as mono-icons.json point to the exact same repository with the only difference being the vendor company (which still is the same) as well as the preview icons.

**Comment by bennetfabian** [comment]
Probably only a duplicate that slipped through but I thought I would mention it. Currently, visual Iconify browsers like icones.js.org might show Mono Icons twice then. 

Could you clarify? @cyberalien

**Comment by cyberalien** [comment]
Yep, there are two of them. No idea how it happened. Thanks a lot for noticing!

Removing one set is not a trivial task. If anyone is using icons from set that I'll remove, their UI might break, which is not acceptable. I'll need to figure out how to hide it without removing it.

**Comment by bennetfabian** [comment]
Yeah, you're right. At first, I didn't think about breaking projects using one of the two sets via Iconify.

**Comment by cyberalien** [comment]
That's why in some icon sets you'll see icons with 'hidden' property, like this (example from tabler.json):
```json
		"track-next": {
			"body": "<path d=\"M13.69 4.198l6.56 6.25c1 .798 1 2.306 0 3.105l-6.564 6.252c-.67.48-1.686 0-1.686-.805v-4l-5.394 4.808C5.937 20.286 5 19.808 5 19V5c0-.812.936-1.285 1.602-.809L12 9V5c0-.816 1.02-1.28 1.69-.802z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
			"hidden": true
		},
```
It means icon was available at some point in icon set source, then for whatever reason was removed. Icons are never removed in Iconify to avoid breaking user's UI. There are at least few hundred of such icons.

Added property `hidden` to `IconifyInfo` type, which will be added to icon set in next update. That should be enough to make sure nothing gets broken for anyone using package, but packages that will support `hidden` property can filter out icon set.

**Comment by cyberalien** [comment]
Done.

Will keep this issue open for a while because I need to update API, which requires taking servers off network one by one to update code base, so I'll do that over the weekend when traffic is lowest.
