### ISSUE TITLE
CoreUI Icons

### ISSUE THREAD

**Issue by mrholek** [iconify/collections-json#6]
Can you add our free icons https://github.com/coreui/coreui-icons ?

**Comment by cyberalien** [comment]
That set looks really nice!

I'm a bit confused with directory structure in repository. There are 4 sets of SVGs: /svg/, /svg/brand/, /svg/flag/ and /svg/free/. Files in /svg/ and in /svg/free/ seems to be duplicated. Which directory has correct source?

Also question about icon grid: brands seem to be 32x32, main icons seem to be 24x24 and flags don't have consistent grid. Is that correct?

**Comment by mrholek** [comment]
/svg/free/ has correct source, icons in /svg/ will be deleted in next release.

In /svg/free/ we have 24x24 in /svg/brands/ 32x32, and flags don't have consistent grid

**Comment by cyberalien** [comment]
Great. Since you already have different prefixes for different sets and they use different grid, I think it can be added as 3 separate sets instead of one, using same prefixes as you have.

So free icons would have "cil-" prefix, brands "cib-", flags "cif-". This way icons will have same names as in your repository, it will be easier to categorise them and first two sets will have consistent grid.

What do you think?

**Comment by mrholek** [comment]
Yes, it's a good idea.

**Comment by cyberalien** [comment]
Great. I'll add them tomorrow.

Sync script automatically updates icons every 24 hours, so once I'll add them, they'll always be up to date.

**Comment by cyberalien** [comment]
Added. Thanks for creating excellent icon set.
